### ISSUE TITLE
CPU usage 80%+

### ISSUE THREAD

**Issue by inspector** [barmstrong/bitcoin-android#12] opened 2011-07-07 18:18 UTC
Like no other app I've seen before it, this one is constantly using from 75%-95% of my phone's CPU also visibly draining the battery. Is it a normal behavior? I can't read code but Is it doing mining calculations?
Also, how is it possible that the entire blockchain fits just 14MB? Is that explained anywhere?

**Comment by NoahZThacker** [comment] 2011-07-07 18:56
I'm having a similar problem.  I have a Dell Streak running dj_steve's custom Android rom.  When I open Bitcoin-Android the circular thinking/downloading thing in the top right corner keeps on spinning forever.  When I close that window the app is still draining my cpu at over 90%.  I tried sending 0.01 BTC to it and it never showed up in the app, but is confirmed on my pc client.  I was wondering if this has something to do with me running a custom rom even though every other app seems to work fine.

**Comment by Rassah** [comment] 2011-07-07 21:07
Had this issue as well. turns out the block chain just takes a LONG time to download. Once the chain is downloaded (took me about 5 hours over 3G), my transfers showed up, new transfers showed up instantly, and the app doesn't seem to be draining the battery at all. Only dues it when I open it and it needs a few seconds to a minute to download the new blockchain piece.

**Comment by brandoniles** [comment] 2011-07-08 03:02
Closing this issue for now. If the behavior keeps happening after the download has finished, please reopen.

**Closed as completed by brandoniles** 2011-07-08 03:02 UTC

**Comment by inspector** [comment] 2011-07-08 23:11
This behavior has indeed stopped but it took over 7 hours on a fast WiFi and a download of over 300MB - so it was practically the same as with the normal official bitcoin client. Now time to test sending some money.
But please, really add a warning about it to new users - this very big and slow download and processing can really confuse new users.
